Repository RedHatInsights/vulnerability-ui, pull requests merged in 2023-11, with the labels that each got.

#2007 feat(RHIF-294): apply cve detail header filters apply to both conventional and immutable systems
  src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.js
  src/Components/PresentationalComponents/CSAwRuleBox/CSAwRuleBox.test.js
  src/Components/PresentationalComponents/CSAwRuleBox/NotVulnerableBox.js
  src/Components/PresentationalComponents/CSAwRuleBox/__snapshots__/CSAwRuleBox.test.js.snap
  src/Components/PresentationalComponents/CVEDetailsPageSummary/CVEDetailsPageSummary.js
  src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
  src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
  src/Store/Reducers/ImmutableDevicesStore.js
Labels: enhancement

#2019 fix(SystemsPage): return useGetSingleDevice back
  src/Helpers/APIHelper.js
Labels: bug

#2028 fix(RHINENG-3366): apply OS filter into URL, show reset filters button
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.js
  src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
  src/Components/SmartComponents/SystemsPage/SystemsPage.js
  src/Helpers/Hooks.js
  src/Helpers/TableToolbarHelper.js
Labels: blocker

#2032 fix(ImmutableDevices): handle RBAC permission properly
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.test.js
Labels: bug

#2035 fix(HybridInventoryTabs): auto switch to edge conditionally
  src/Components/SmartComponents/CVEDetailsPage/CVEDetailTableTitle.js
  src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
  src/Components/SmartComponents/CVEDetailsPage/CveDetailTableTitle.test.js
  src/Components/SmartComponents/CVEDetailsPage/cveDetailHelpers.js
  src/Components/SmartComponents/CVEDetailsPage/cveDetailHelpers.test.js
  src/Components/SmartComponents/HybridInventory/HybridInventoryTabs.js
  src/Components/SmartComponents/HybridInventory/HybridInventoryTabs.test.js
Labels: blocker

#2040 feat(RHINENG-3415): enforces groups info to be fetched from edge cond…
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.js
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/ImmutableDevices.test.js
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.js
  src/Components/SmartComponents/HybridInventory/ImmutableDevicesTab/helpers.test.js
  src/Helpers/CVEHelper.js
Labels: enhancement

#2041 chore(RHINENG-2802): Remove inventory groups feature flag
  src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
  src/Components/SmartComponents/SystemsPage/SystemsPage.js
Labels: chore

#2002 feat(RHIF-283): extend CVE systems filter with edge
  config/setupTests.js
  package-lock.json
  package.json
  src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/AffectingFilter.js
  src/Components/SmartComponents/CVEs/CVEs.js
  src/Components/SmartComponents/CVEs/CVEs.test.js
  src/Components/SmartComponents/CVEs/CVEsAssets.js
  src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
  src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
  src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
  src/Components/SmartComponents/Dashbar/Dashbar.js
  src/Components/SmartComponents/Modals/ReportConfigModal.js
  src/Components/SmartComponents/Modals/ReportConfigModal.test.js
  src/Components/SmartComponents/Modals/__snapshots__/ReportConfigModal.test.js.snap
  src/Components/SmartComponents/Reports/Common/firstPagePDF.js
  src/Components/SmartComponents/Reports/ReportsPage.js
  src/Components/SmartComponents/Reports/ReportsPage.test.js
  src/Components/SmartComponents/Reports/__snapshots__/ReportsPage.test.js.snap
  src/Helpers/APIHelper.js
  src/Helpers/DownloadReport.js
  src/Helpers/DownloadReport.test.js
  src/Helpers/Hooks.js
  src/Helpers/ReportsHelper.js
  src/Helpers/TableToolbarHelper.js
  src/Helpers/constants.js
  src/Messages.js
  src/Store/Actions/Actions.js
  src/Store/Reducers/CVEsStore.js
  src/Utilities/VulnerabilityRoutes.js
Labels: enhancement
