Repository RedHatInsights/vulnerability-ui, pull requests merged in 2023-01, with the labels that each got.

#1840 chore(Shared dependencies): Align versions of redux
  package-lock.json
  package.json
  src/Components/SmartComponents/CVEDetailsPage/__snapshots__/CveDetailsPage.test.js.snap
Labels: dependencies

#1849 chore: Refactor column management to use hooks
  src/Components/SmartComponents/CVEs/CVEs.js
  src/Components/SmartComponents/CVEs/CVEs.test.js
  src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
  src/Components/SmartComponents/CVEs/__snapshots__/CVEs.test.js.snap
  src/Components/SmartComponents/SystemCves/SystemCveTableToolbar.js
  src/Components/SmartComponents/SystemCves/SystemCves.js
  src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTable.js
  src/Components/SmartComponents/SystemsExposedTable/SystemsExposedTableToolbar.js
  src/Components/SmartComponents/SystemsPage/SystemsPage.js
  src/Components/SmartComponents/SystemsPage/SystemsTableToolbar.js
  src/Helpers/Hooks.js
Labels: chore

#1854 feat(VULN-2481): Add new cluster link
  locales/en.json
  package.json
  src/App.scss
  src/Components/PresentationalComponents/CVEDetailsPageDescription/CVEDetailsPageDescription.js
  src/Components/PresentationalComponents/CVEDetailsPageDescription/__snapshots__/CVEDetailsPageDescription.test.js.snap
  src/Components/PresentationalComponents/CVEDetailsPageSummary/__snapshots__/CVEDetailsPageSummary.test.js.snap
  src/Components/SmartComponents/CVEDetailsPage/CVEDetailsPage.js
  src/Components/SmartComponents/CVEDetailsPage/CveDetailsPage.test.js
  src/Helpers/APIHelper.js
  src/Helpers/CVEHelper.js
  src/Helpers/CVEHelper.test.js
  src/Helpers/constants.js
  src/Messages.js
  src/Store/ActionTypes.js
  src/Store/Actions/Actions.js
  src/Store/Reducers/CVEDetailsPageStore.js
Labels: enhancement
