Repository RedHatInsights/vulnerability-ui, pull requests merged in 2025-05, with the labels that each got.

#2236 feat(RHINENG-16847): create modal for os report
  src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/ImpactFilter.js
  src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.js
  src/Components/SmartComponents/Modals/OsExposureReportModal/LifecycleSelect.test.js
  src/Components/SmartComponents/Modals/OsExposureReportModal/OsExposureReportModal.js
  src/Components/SmartComponents/Modals/OsExposureReportModal/OsExposureReportModal.test.js
  src/Components/SmartComponents/Modals/OsExposureReportModal/osExposureReport.fixtures.js
  src/Components/SmartComponents/Reports/ReportsPage.js
  src/Helpers/APIHelper.js
  src/Helpers/constants.js
Labels: enhancement

#2239 refactor: Improve CVSS vector component code clarity
  src/Components/PresentationalComponents/CvssVector/CvssVector.js
Labels: chore

#2245 feat(RHINENG-16844): Add 'Applies to OS' filter
  src/App.scss
  src/Components/PresentationalComponents/Filters/PrimaryToolbarFilters/AppliesToOSFilter.js
  src/Components/SmartComponents/CVEs/CVEs.cy.js
  src/Components/SmartComponents/CVEs/CVEs.js
  src/Components/SmartComponents/CVEs/CVEs.test.js
  src/Components/SmartComponents/CVEs/CVEsTableToolbar.js
  src/Components/SmartComponents/CVEs/CVEsTableToolbar.test.js
  src/Components/SmartComponents/Reports/Common/TablePage.js
  src/Helpers/TableToolbarHelper.js
  src/Helpers/constants.js
  src/Messages.js
  src/Store/Reducers/CVEsStore.js
Labels: enhancement

#2264 feat: Improve dashbar skeleton, reapply skeleton when loading again
  src/Components/SmartComponents/Dashbar/Dashbar.js
  src/Components/SmartComponents/LandingPage/__snapshots__/LandingPage.test.js.snap
Labels: enhancement

#2272 chore(deps): update cypress to 14 4
  cypress/support/component.js
  package-lock.json
  package.json
Labels: dependencies
